### ISSUE TITLE
Specify past-version of protactor?

### ISSUE THREAD

**Issue by mbijon** [jacobwsmith/sanity-test#1]
This isn't working with a modern version of protractor. It appears the getInstance() here, https://github.com/jacobwsmith/sanity-test/blob/master/sanity-test.js#L31, should just be `var ptor = browser;` since ~v1.5

**Comment by jacobwsmith** [comment]
Hi Mike,

I was using an old version of protractor. Thanks for pointing this out.
I've made the update to github. I look forward to meeting with you.

Cheers,

Jake
